server:
  port: 443
  domain: rest.hellouni.co.kr

### ssl ###
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-store-password: crew1207

### jpa ###
spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB

## datasource ###
  datasource:
    url: jdbc:mysql://photosend-mysql-rds.cq2lmghf0zft.ap-northeast-2.rds.amazonaws.com:3306/photosend
    driver-class-name: com.mysql.jdbc.Driver

## DB for test ###
#  h2:
#    console:
#      path: /h2-console
#      enabled: true

### photo send application setting ###
photosend:
  credential:
    admin:
      file-path: .photosend/adminCredential.txt
    datasource:
      file-path: .photosend/databaseAccount.txt

  jwt:
    secretkey: peoplus
    expiredtime: 999999999999999999

  aws:
    s3:
      bucket-name: photosend-server
      upload-path:
        prefix: https://photosend-server.s3.ap-northeast-2.amazonaws.com/

  file:
    upload-path:
