server:
  port: 443
#  domain: rest.hellouni.co.kr # 배포시 도메인
  domain: test.hellouni.co.kr # 테스트시 도메인

### ssl ###
  ssl:
#    key-store: classpath:keystore/keystore.p12 # 배포시 keyfile
    key-store: classpath:keystore/keystore_test.p12
    key-store-type: PKCS12
    key-store-password: crew1207

### jpa ###
spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB

## datasource ###
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

# DB for test ###
#  h2:
#    console:
#      path: /h2-console
#      enabled: true

### photo send application setting ###
photosend:
  credential:
    admin:
      file-path: .photosend/adminCredential.txt
    datasource:
      file-path: .photosend/databaseAccount.txt
    mail:
      file-path: .photosend/mailCredential.txt

  jwt:
    secretkey: peoplus
    expiredtime: 999999999999999999

  aws:
    s3:
      bucket-name: photosend-server
      upload-path:
        prefix: https://photosend-server.s3.ap-northeast-2.amazonaws.com/

  file:
    upload-path: