############ 공통 설정 및 Active Profile 설정 ###############
spring:
  profiles:
    active: deploy
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false


---

################ TEST SERVER 환경 ################
server:
  port: 443
  domain: test.phsend.com

  ### ssl ###
  ssl:
    key-store: classpath:keystore/keystore_test.p12
    key-store-type: PKCS12
    key-store-password: crew1207

spring:
  profiles: test
  jackson:
    time-zone: Asia/Seoul

  ### jpa ###
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB

# DB for test ###
#  h2:
#    console:
#      path: /h2-console
#      enabled: true

### photo send application setting ###
photosend:
  bundle: org.reactjs.native.PhotoSend

  credential:
    admin:
      file-path: .photosend/webAdminCredential.txt
    datasource:
      file-path: .photosend/databaseAccount.txt
    mail:
      file-path: .photosend/mailCredential.txt
    apns:
      file-path: .photosend/AuthKey_8NYW4PKBLS.p8

  jwt:
    secretkey: peoplus
    expiredtime: 999999999999999999

  aws:
    s3:
      bucket-name:
        users-upload: photosend-server
        app-img: photosend-server-app-img

      upload-path:
        prefix:
          users-upload: https://photosend-server.s3.ap-northeast-2.amazonaws.com/
          app-img: https://photosend-server-app-img.s3.ap-northeast-2.amazonaws.com/

  file:
    upload-path:

---

################ LOCAL SERVER 환경 ################

server:
  port: 80

spring:
  profiles: local

  ### jpa ###
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB

# DB for test ###
#  h2:
#    console:
#      path: /h2-console
#      enabled: true

### photo send application setting ###
photosend:
  bundle: org.reactjs.native.PhotoSend

  credential:
    admin:
      file-path: .photosend/webAdminCredential.txt
    datasource:
      file-path: .photosend/databaseAccount.txt
    mail:
      file-path: .photosend/mailCredential.txt
    apns:
      file-path: .photosend/AuthKey_8NYW4PKBLS.p8

  jwt:
    secretkey: peoplus
    expiredtime: 999999999999999999

  aws:
    s3:
      bucket-name:
        users-upload: photosend-server
        app-img: photosend-server-app-img

      upload-path:
        prefix:
          users-upload: https://photosend-server.s3.ap-northeast-2.amazonaws.com/
          app-img: https://photosend-server-app-img.s3.ap-northeast-2.amazonaws.com/

  file:
    upload-path:




---

################ DEPLOY SERVER 환경 ################
server:
  port: 443
  domain: rest.phsend.com

  ### ssl ###
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-store-password: crew1207


spring:
  profiles: deploy

  ### jpa ###
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB

# DB for test ###
#  h2:
#    console:
#      path: /h2-console
#      enabled: true

### photo send application setting ###
photosend:
  bundle: org.reactjs.native.PhotoSend

  credential:
    admin:
      file-path: .photosend/webAdminCredential.txt
    datasource:
      file-path: .photosend/databaseAccount.txt
    mail:
      file-path: .photosend/mailCredential.txt
    apns:
      file-path: .photosend/AuthKey_8NYW4PKBLS.p8

  jwt:
    secretkey: peoplus
    expiredtime: 999999999999999999

  aws:
    s3:
      bucket-name:
        users-upload: photosend-server
        app-img: photosend-server-app-img

      upload-path:
        prefix:
          users-upload: https://photosend-server.s3.ap-northeast-2.amazonaws.com/
          app-img: https://photosend-server-app-img.s3.ap-northeast-2.amazonaws.com/

  file:
    upload-path:

