############ 공통 설정 및 Active Profile 설정 ###############
spring:
  profiles:
    active: deploy
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false


---
################ TEST SERVER 환경 ################
server:
  port: 443
  domain: test.phsend.com

  ### ssl ###
  ssl:
    key-store: classpath:keystore/keystore_test.p12
    key-store-type: PKCS12
    key-store-password: crew1207

spring:
  profiles: test
  jackson:
    time-zone: Asia/Seoul

  ### jpa ###
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB

---

################ LOCAL SERVER 환경 ################

server:
  port: 80

spring:
  profiles: local

  ### jpa ###
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB

---

################ DEPLOY SERVER 환경 ################
server:
  port: 443
  domain: rest.phsend.com

  ### ssl ###
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-store-password: crew1207


spring:
  profiles: deploy

  ### jpa ###
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB
